fixtures:
  repositories:
    stdlib:  https://github.com/puppetlabs/puppetlabs-stdlib.git
    wget:    https://github.com/maestrodev/puppet-wget
    inifile: https://github.com/puppetlabs/puppetlabs-inifile
  symlinks:
    puppet_ent_agent: "#{source_dir}"
